---
title: "Running times"
output: html_notebook
---

Loading dependencies
```{r}
library(breastCancerVDX)
library(microbenchmark)
library(Biobase)
library(dplyr)
library(ggplot2)
library(gpowerr)
```

Loading data
```{r}
data(vdx)
expressions <- t(exprs(vdx))
```

Select level of sparsity, find corresponding rho and run benchmark again.
```{r}
i <- 20000
data <- expressions[, 1:i]
a <- auto_gpower(data, k = 2, prop_sparse = 0.5, reg = 'l1')
b <- auto_gpower(data, k = 2, prop_sparse = 0.5, reg = 'l0')

```


Benchmark for gpower()
```{r}
i <- 200
data <- expressions[, 1:i]
df <- print(microbenchmark(gpower(data, k = 2, rho = 0.0488, reg = 'l1'),
                           gpower(data, k = 2, rho = 0.00293, reg = 'l0'),
                           times = 50), unit = "s")[, c("expr", "mean")]
df["i"] <- i
df["method"] <- c("single-unit l1", "single-unit l0")

result <- df

```

```{r}
i <- 2000
data <- expressions[, 1:i]
df <- print(microbenchmark(gpower(data, k = 2, rho = 0.04004, reg = 'l1'),
                           gpower(data, k = 2, rho = 0.00171 , reg = 'l0'),
                           times = 20), unit = "s")[, c("expr", "mean")]
df["i"] <- i
df["method"] <- c("single-unit l1", "single-unit l0")

result <- bind_rows(result, df)

```

```{r}
i <- 20000
data <- expressions[, 1:i]
df <- print(microbenchmark(gpower(data, k = 2, rho = 0.03418, reg = 'l1'),
                           gpower(data, k = 2, rho = 0.00134, reg = 'l0'),
                           times = 10), unit = "s")[, c("expr", "mean")]
df["i"] <- i
df["method"] <- c("single-unit l1", "single-unit l0")

result <- bind_rows(result, df)
```

```{r}
png("figures/running_times.png", width = 600, height = 370, res=90)

ggplot(result, aes(x=i, y=mean, color=method)) +
  geom_line() +
  scale_x_log10(breaks = c(100, 1000, 10000, 20000)) +
  scale_y_log10() +
  labs(x = "log number of variables", y = "log running time (seconds)", 
       title = "Mean running times on the VDX expressions dataset ", 
       subtitle = "to obtain a 50% sparse weights matrix",
       color = "Method")
  

dev.off()
```

